module.exports = function(classifier) {

  classifier.addDocument("Why I Changed My Mind On Weed",'drugs')
  classifier.addDocument("Python for Android",'programming')
  classifier.addDocument("Create a font from your own handwriting",'programming')
  classifier.addDocument("John Carmack joins Oculus as CTO",'business')
  classifier.addDocument("How to build a procedural city in WebGL",'programming')
  classifier.addDocument("Elon Musk Just May Have To Develop an Electric Supersonic Jet",'business')
  classifier.addDocument("Why is cycling so popular in the Netherlands?",'culture')
  classifier.addDocument("The costly criminalisation of the mentally ill",'culture')
  classifier.addDocument("How to Convince Investors",'business')
  classifier.addDocument("Google supports MariaDB",'programming')
  classifier.addDocument("The most interesting things I've learnt about learning",'education')
  classifier.addDocument("Shutting Down a Dream",'blog')
  classifier.addDocument("Delicious Menus With Hatchware and CouchApps on Cloudant",'programming')
  classifier.addDocument("Russian Man Changes Small Print in Credit Card Agreement, Then Sues",'business')
  classifier.addDocument("London Startup Map",'culture')
  classifier.addDocument("Does Entrepreneurial Experience Dim Future Job Prospects?",'business')
  classifier.addDocument("Queueing in the Linux Network Stack",'programming')
  classifier.addDocument("PHP Weekly – August 8, 2013",'programming')
  classifier.addDocument("Listen to Wikipedia",'blog')
  classifier.addDocument("SideProjectors – Marketplace to buy and sell side projects",'business')
  // classifier.addDocument("Why Can't Science Keep Up With Sports Doping?",'drugs')
  // classifier.addDocument("Steps To $5,000 In Monthly Recurring Revenue",'business')
  // classifier.addDocument("NYC Developer Bootcamp Fullstack Academy",'education')
  // classifier.addDocument("Android AOSP maintainer quits",'programming')
  // classifier.addDocument("Slashdot founder Rob Malda on why there won’t be another Hacker News",'blog')
  // classifier.addDocument("Software Updates: Courgette",'programming')
  // classifier.addDocument("Show HN: Raw Image Storage for photographers using S3 and Glacier",'business')
  // classifier.addDocument("Rediscala: Non-blocking Redis driver for Scala",'programming')
  // classifier.addDocument("Google on games: \"we've really only just started\"",'blog')
  // classifier.addDocument("Space station poised to launch open-source satellites",'drugs')
  // classifier.addDocument("Ask HN: Which companies are looking for Rails devs in Seattle?", "jobs")
  // classifier.addDocument("NSA to cut system administrators by 90 percent to limit data access", "politics")
  // classifier.addDocument("Limited time free trial of ParElastic database scaling solution", "programming")
  // classifier.addDocument("It appears big data can make us better artists", "blog")
  // classifier.addDocument("Double Robotics Unboxing by Leo Laporte", "programming")
  // classifier.addDocument("Silent Circle following Lavabit's lead. Shutting service down.", "business")
  // classifier.addDocument("At Automattic Employees All Work From Home And Travel To Exotic Locations", "blog")
  // classifier.addDocument("Tax Startup bought by Intuit before its Techstars demo day", "business")
  // classifier.addDocument("George Saunder's Advice to Graduates", "education")
  // classifier.addDocument("AA Battery Test", "programming")
  // classifier.addDocument("Yahoo pays David Karp $110M", "business")
  // classifier.addDocument("Why Max Levchin's Glow is about much more than fertility", "drugs")
  // classifier.addDocument("The NSA Intends To Fire 90% Of Their System Administrators", "politics")
  // classifier.addDocument("Just two ways to make Firefox more secure", "programming")
  // classifier.addDocument("Gadgets that make your life lot less miserable", "programming")
  // classifier.addDocument("Google’s Android Seizes Smartphone Market", "business")
  // classifier.addDocument("Penny Pinching in the cloud: When do Azure Websites make sense?", "business")
  // classifier.addDocument("Average home tops $1 million in Silicon Valley", "business")
  // classifier.addDocument("Show HN: The Adventure Playbook - email signup conversion results The Number One Goal of Your Website", "blog")
  // classifier.addDocument("Boycotting a company?", "culture")
  // classifier.addDocument("Bill Gates's barbed comments pop Google's broadband balloons", "business")
  // classifier.addDocument("Current HoR reps who voted against Patriot act + all renewals + for Amash Amend", "politics")
  // classifier.addDocument("FBI Special Agent visit Thursday August 8th", "politics")
  // classifier.addDocument("Part 2: Surface RT v/s iPad?", "blog")
  // classifier.addDocument("Ex-Valve employee exposes ‘high school clique’ management structure", "business")
  // classifier.addDocument("Windows Phone App Studio", "programming")

  classifier.train()

}
